name: heros-core
version: ${project.version}
main: net.herospvp.heroscore.HerosCore
authors: [ Niketion, Sorridi ]
load: STARTUP
depend:
  - database-lib
  - PlaceholderAPI
  - ProtocolLib
commands:
  coins:
  coinsadmin:
    aliases: [ca]
    permission: herospvp.admin
